/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  VRFConsumerInterface,
  VRFConsumerInterfaceInterface,
} from "../../contracts/VRFConsumerInterface";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256[]",
        name: "_randomNumbers",
        type: "uint256[]",
      },
      {
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
    ],
    name: "vrfCallback",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class VRFConsumerInterface__factory {
  static readonly abi = _abi;
  static createInterface(): VRFConsumerInterfaceInterface {
    return new Interface(_abi) as VRFConsumerInterfaceInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): VRFConsumerInterface {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as VRFConsumerInterface;
  }
}
